version: "3"

services:

  realm:
    image: realm
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JVM_ARGS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - database

  database:
    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
